services:
  api:
    restart: always
    image: qbituniverse/iot-trafficlights-api:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-trafficlights-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ApiConfiguration__Environment=${ENVIRONMENT}
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=SQLite
      - ApiConfiguration__Repository__SQLite__Url=/data/db/IotTrafficLights.db
      - ApiConfiguration__Modules__TrafficControl__Type=${GPIO}
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${API_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-web:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-trafficlights-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - WebConfiguration__Environment=${ENVIRONMENT}
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=SQLite
      - WebConfiguration__Repository__SQLite__Url=/data/db/IotTrafficLights.db
      - WebConfiguration__Api__Url=http://${COMPOSE_PROJECT_NAME}_iot-trafficlights-api:8080
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${WEB_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  console:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-console:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-trafficlights-console
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConsoleConfiguration__Environment=${ENVIRONMENT}
      - ConsoleConfiguration__LogLevel__Console=Information
      - ConsoleConfiguration__LogLevel__Database=Error
      - ConsoleConfiguration__Repository__Type=SQLite
      - ConsoleConfiguration__Repository__SQLite__Url=/data/db/IotTrafficLights.db
      - ConsoleConfiguration__Modules__TrafficControl__Type=${GPIO}
      - ConsoleConfiguration__Modules__TrafficSensor__Type=${GPIO}
      - ConsoleConfiguration__Run=${RUN}
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  sqlitebrowser:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-trafficlights-sqlitebrowser
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${DB_PORT}:3000
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

networks:
  iot-trafficlights:
    driver: bridge