services:
  api:
    restart: always
    image: qbituniverse/iot-trafficlights-api:latest
    container_name: iot-trafficlights-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__Environment=Development
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=SQLite
      - ApiConfiguration__Repository__SQLite__Url=/data/db/IoT-TrafficLights.db
      - ApiConfiguration__Modules__TrafficControl__Type=Mock
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 8010:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-web:latest
    container_name: iot-trafficlights-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - WebConfiguration__Environment=Development
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=SQLite
      - WebConfiguration__Repository__SQLite__Url=/data/db/IoT-TrafficLights.db
      - WebConfiguration__Api__Url=http://iot-trafficlights-api:8080
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 8015:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  console:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-console:latest
    container_name: iot-trafficlights-console
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ConsoleConfiguration__Environment=Development
      - ConsoleConfiguration__LogLevel__Console=Information
      - ConsoleConfiguration__LogLevel__Database=Error
      - ConsoleConfiguration__Repository__Type=SQLite
      - ConsoleConfiguration__Repository__SQLite__Url=/data/db/IoT-TrafficLights.db
      - ConsoleConfiguration__Modules__TrafficControl__Type=Mock
      - ConsoleConfiguration__Modules__TrafficSensor__Type=Mock
      - ConsoleConfiguration__Run=RunTrafficSensor
    volumes:
      - ${DB_DIR}:/data/db
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  sqlitebrowser:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: iot-trafficlights-sqlitebrowser
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 3019:3000
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

networks:
  iot-trafficlights:
    driver: bridge