services:
  db:
    restart: always
    image: mysql:latest
    container_name: iot-trafficlights-mysql
    environment:
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=IotTrafficLights
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    ports:
      - 3319:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 120s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights
  
  api:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-api:latest
    container_name: iot-trafficlights-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__Environment=Development
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=MySql
      - ApiConfiguration__Repository__MySql__Url=Server=iot-trafficlights-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotTrafficLights
      - ApiConfiguration__Modules__TrafficControl__Type=Mock
    ports:
      - 8010:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-web:latest
    container_name: iot-trafficlights-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - WebConfiguration__Environment=Development
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=MySql
      - WebConfiguration__Repository__MySql__Url=Server=iot-trafficlights-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotTrafficLights
      - WebConfiguration__Api__Url=http://iot-trafficlights-api:8080
    ports:
      - 8015:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  console:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-trafficlights-console:latest
    container_name: iot-trafficlights-console
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ConsoleConfiguration__Environment=Development
      - ConsoleConfiguration__LogLevel__Console=Information
      - ConsoleConfiguration__LogLevel__Database=Error
      - ConsoleConfiguration__Repository__Type=MySql
      - ConsoleConfiguration__Repository__MySql__Url=Server=iot-trafficlights-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotTrafficLights
      - ConsoleConfiguration__Modules__TrafficControl__Type=Mock
      - ConsoleConfiguration__Modules__TrafficSensor__Type=Mock
      - ConsoleConfiguration__Run=RunTrafficSensor
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

networks:
  iot-trafficlights:
    driver: bridge