services:
  api:
    image: qbituniverse/iot-trafficlights-api:latest
    restart: always
    container_name: iot-trafficlights-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__Environment=Development
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=SQLite
      - ApiConfiguration__Repository__SQLite__Url=/data/db/TrafficLights.db
      - ApiConfiguration__Modules__TrafficControl__Type=Mock
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 8100:8080
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  web:
    image: qbituniverse/iot-trafficlights-web:latest
    restart: always
    container_name: iot-trafficlights-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - WebConfiguration__Environment=Development
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=SQLite
      - WebConfiguration__Repository__SQLite__Url=/data/db/TrafficLights.db
      - WebConfiguration__Api__Url=http://iot-trafficlights-api:8080
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 8110:8080
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

  console:
    image: qbituniverse/iot-trafficlights-console:latest
    restart: always
    container_name: iot-trafficlights-console
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ConsoleConfiguration__Environment=Development
      - ConsoleConfiguration__LogLevel__Console=Information
      - ConsoleConfiguration__LogLevel__Database=Error
      - ConsoleConfiguration__Repository__Type=SQLite
      - ConsoleConfiguration__Repository__SQLite__Url=/data/db/TrafficLights.db
      - ConsoleConfiguration__Modules__TrafficControl__Type=Mock
      - ConsoleConfiguration__Modules__TrafficSensor__Type=Mock
      - ConsoleConfiguration__Run=RunTrafficSensor
    volumes:
      - ${DB_DIR}:/data/db
    tty: true
    privileged: true
    networks:
      - iot-trafficlights

networks:
  iot-trafficlights:
    driver: bridge