FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

LABEL version="8.0" \
	  description="Image to create IoT Traffic Lights Console" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app

RUN apt-get update && apt-get install -y curl

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["IoT.TrafficLights.Console/IoT.TrafficLights.Console.csproj", "IoT.TrafficLights.Console/"]
RUN dotnet restore "IoT.TrafficLights.Console/IoT.TrafficLights.Console.csproj"

COPY . .
WORKDIR "/src/IoT.TrafficLights.Console"
RUN dotnet build "IoT.TrafficLights.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IoT.TrafficLights.Console.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "IoT.TrafficLights.Console.dll"]