FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

LABEL version="8.0" \
	  description="Image to create IoT Traffic Lights Console" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TrafficLights.Console/TrafficLights.Console.csproj", "TrafficLights.Console/"]
RUN dotnet restore "TrafficLights.Console/TrafficLights.Console.csproj"

COPY . .
WORKDIR "/src/TrafficLights.Console"
RUN dotnet build "TrafficLights.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TrafficLights.Console.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "TrafficLights.Console.dll"]